name: Ansible Deployment 
on: 
    # push:
    workflow_dispatch: 
env:
    ANSIBLE_HOST_KEY_CHECKING: false
    ANSIBLE_REMOTE_USER: ec2-user

permissions: 
    id-token: write
jobs:
    ansible-depoy:
        runs-on: ubuntu-latest
        steps:
            - name: Cache deps
              id: cache-deps
              uses: actions/cache@v4
              with:
                path: |
                  ~/.ansible
                  ~/.cache
                  /usr/local/lib/
                key: ${{ runner.os }}-deps

            - name: Clonning The Repo to the runner
              uses: actions/checkout@v3
            
            - name: Install python3
              if: steps.cache-deps.outputs.cache-hit != 'true'
              uses: actions/setup-python@v5 
              with:
                python-version: '3.10'

            - name: Installing Ansible (latest) and boto3 modules
              if: steps.cache-deps.outputs.cache-hit != 'true'
              shell: pwsh
              run: |
                python -m pip install --upgrade pip
                pip install ansible boto3 botocore
            
            - name: Installing Ansible Galaxy Collection (amazon.aws)
              if: steps.cache-deps.outputs.cache-hit != 'true'
              shell: pwsh
              run: |
                ansible-galaxy collection install amazon.aws

            
            - name: Configure AWS Credentials from AWS account
              id: login
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume:  ${{ secrets.AWS_ROLE }}
                aws-region: ${{ secrets.AWS_REGION }}
                role-session-name: GH-OIDC-TERRAFORM
                output-credentials: true

            - name: Running Ansible inventory file
              shell: pwsh
              run: |
                ansible-inventory --inventory inv.aws_ec2.yml --list
            - name: Keep ssh key in a file 
              shell: pwsh
              run: |
                Set-Content -Path mykey -Value '${{ secrets.ANSIBLE_SSH_KEY }}'
                chmod 400 mykey
            - name: Running Playbook
              shell: pwsh 
              run: ansible-playbook --inventory  inv.aws_ec2.yml --private-key mykey  ./ansible/install_cloud_watch_agent.yaml